### ISSUE TITLE
Lacking script to quickly open the map

### ISSUE THREAD

**Issue by david-wm-sanders** [rwr-community-dev/_muttrah_map_project#6]
Could have a script that opens that map using map= and also passes the debugmode, no_ai, etc commands

**Comment by melbit-paulcameron** [comment]
Can probably knock this one over with a combination of [this](https://github.com/rwr-community-dev/_muttrah_map_project/blob/anoshi/README.md#usage) + [this](https://runningwithrifles.gamepedia.com/How_to_create_new_maps#Testing_your_map_in_Running_with_Rifles)

**Comment by david-wm-sanders** [comment]
@anoshi i have done a basic python3 script to do this as this was the easiest method for me :)

i derived my solution from the way rwrs provides the links to open the game to a specific server in discord. as it is python3 it should be cross-platform out of the gate but the downside is that it requires people to actually have python3.6+ XD

you are welcome to write a bash script to provide equivalent functionality and add it to repo if you desire. if windows users who don't have python3 installed want a batch script... they can write it themselves lol 🤣
